apiVersion: v1
kind: Pod
metadata:
  app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    - containerPort: 443
    
---

apiVersion: v1
kind: Pod
metadata:
  app: mongo
spec:
  containers:
  - name: mongo
    image: mongo
    ports:
    - containerPort: 27017
